name: base-ci

env:
  PYTHON_VERSION: '3.13.3'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.3'

    - name: Install pre-commit
      run: pip install -r ${{ github.workspace }}/.config/requirements.txt
